Repository cmu-db/noisepage-pilot, pull requests merged in 2022-01, with the labels that each got.

#9 Bump from psycopg2 to psycopg3.
  action/recommendation/index_picker.py
  requirements.txt
Labels: best-practice

#10 Add the Pilot component.
  bootstrap.sql
  dodo.py
  pilot/bootstrap_tables.sql
  pilot/client.py
  pilot/daemon.py
  pilot/protocol.py
Labels: feature

#11 Update forecasting: sklearn DBSCAN for clustering, LSTM for predictions.
  dodo.py
  forecast/Sine_Forecast.ipynb
  forecast/clusterer.py
  forecast/forecaster.py
  forecast/model.py
  forecast/preprocessor.py
Labels: ready-to-merge, feature

#12 Behavior Modeling Framework
  .flake8
  .github/workflows/ci.yaml
  .gitignore
  README.md
  action/recommendation/index_picker.py
  behavior/README.md
  behavior/__init__.py
  behavior/__main__.py
  behavior/datagen/__init__.py
  behavior/datagen/gen.py
  behavior/modeling/__init__.py
  behavior/modeling/inference.py
  behavior/modeling/model.py
  behavior/modeling/train.py
  behavior/plans/__init__.py
  behavior/plans/diff.py
  config/behavior/benchbase/auctionmark_config.xml
  config/behavior/benchbase/epinions_config.xml
  config/behavior/benchbase/noop_config.xml
  config/behavior/benchbase/seats_config.xml
  config/behavior/benchbase/sibench_config.xml
  config/behavior/benchbase/smallbank_config.xml
  config/behavior/benchbase/tatp_config.xml
  config/behavior/benchbase/tpcc_config.xml
  config/behavior/benchbase/tpch_config.xml
  config/behavior/benchbase/twitter_config.xml
  config/behavior/benchbase/voter_config.xml
  config/behavior/benchbase/wikipedia_config.xml
  config/behavior/benchbase/ycsb_config.xml
  config/behavior/default.yaml
  config/behavior/postgres/postgresql.conf
  docs/behavior/behavior_modeling_pipeline.svg
  dodo.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: ready-to-merge, feature

#14 Increase line length from 88 to 120.
  action/generation/generate_create_index_tpcc.py
  action/recommendation/index_picker.py
  behavior/__main__.py
  behavior/datagen/gen.py
  behavior/modeling/inference.py
  behavior/modeling/model.py
  behavior/modeling/train.py
  behavior/plans/diff.py
  dodo.py
  forecast/clusterer.py
  forecast/forecaster.py
  forecast/model.py
  forecast/preprocessor.py
  pilot/client.py
  pilot/protocol.py
  pyproject.toml
Labels: best-practice

#16 Fix README Install Instructions and fix scikit-learn requirement
  README.md
  dodo.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: ready-for-review

#17 Fix docstring type typo in gen.py.
  behavior/datagen/gen.py
Labels: best-practice

#19 Send TScout output to stdout and stderr during data generation.
  behavior/datagen/gen.py
Labels: ready-for-review, feature

#18 Update BenchBase configs to use READ_COMMITTED. Reset TPC-C runtime to 60s.
  config/behavior/benchbase/auctionmark_config.xml
  config/behavior/benchbase/epinions_config.xml
  config/behavior/benchbase/noop_config.xml
  config/behavior/benchbase/seats_config.xml
  config/behavior/benchbase/sibench_config.xml
  config/behavior/benchbase/smallbank_config.xml
  config/behavior/benchbase/tatp_config.xml
  config/behavior/benchbase/tpcc_config.xml
  config/behavior/benchbase/tpch_config.xml
  config/behavior/benchbase/twitter_config.xml
  config/behavior/benchbase/voter_config.xml
  config/behavior/benchbase/wikipedia_config.xml
  config/behavior/benchbase/ycsb_config.xml
Labels: ready-for-review

#22 Split dodo.py into a dodos/ folder. Fix paths. Add tasks.
  dodo.py
  dodos/README.md
  dodos/__init__.py
  dodos/action.py
  dodos/behavior.py
  dodos/benchbase.py
  dodos/ci.py
  dodos/forecast.py
  dodos/noisepage.py
  dodos/pilot.py
  requirements.txt
Labels: infrastructure, best-practice

#23 Add filtered tables for TPC-C create index actions.
  action/generation/generate_create_index_tpcc.py
  dodos/action.py
Labels: feature

#24 Add model inference via a local Flask app.
  behavior/__main__.py
  behavior/microservice/__init__.py
  behavior/microservice/app.py
  behavior/modeling/model.py
  dodos/behavior.py
  pyproject.toml
  requirements.txt
Labels: feature

#25 Rewrite default BenchBase configuration URLs.
  config/behavior/benchbase/auctionmark_config.xml
  config/behavior/benchbase/epinions_config.xml
  config/behavior/benchbase/noop_config.xml
  config/behavior/benchbase/seats_config.xml
  config/behavior/benchbase/sibench_config.xml
  config/behavior/benchbase/smallbank_config.xml
  config/behavior/benchbase/tatp_config.xml
  config/behavior/benchbase/tpcc_config.xml
  config/behavior/benchbase/tpch_config.xml
  config/behavior/benchbase/twitter_config.xml
  config/behavior/benchbase/voter_config.xml
  config/behavior/benchbase/wikipedia_config.xml
  config/behavior/benchbase/ycsb_config.xml
Labels: bug

#26 Fix dodo quirks in benchbase_run and action_recommendation.
  dodos/action.py
  dodos/benchbase.py
Labels: bug

#27 Add inference via microservice to database_game.
  action/selection/open_spiel/CMakeLists.txt
  action/selection/open_spiel/database.cc
  action/selection/open_spiel/database.h
  action/selection/open_spiel/database_game.cc
Labels: feature

#21 Behavior Modeling - Differencing and Training Improvements + Fixes
  behavior/README.md
  behavior/__init__.py
  behavior/datagen/gen.py
  behavior/modeling/model.py
  behavior/modeling/train.py
  behavior/plans/diff.py
  config/behavior/default.yaml
  config/behavior/postgres/postgresql.conf
Labels: feature

#29 Add support for `doit ci_python check=true`, use in GitHub Actions.
  .github/workflows/ci.yaml
  dodos/benchbase.py
  dodos/ci.py
Labels: best-practice

#30 Parameterize workload forecasting arguments (with defaults).
  dodos/forecast.py
  forecast/forecaster.py
  forecast/preprocessor.py
Labels: feature, best-practice

#28 Add demo/mvp.sh.
  action/recommendation/index_picker.py
  action/selection/open_spiel/database.cc
  behavior/microservice/app.py
  demo/mvp.sh
  dodos/behavior.py
  dodos/benchbase.py
  dodos/noisepage.py
  pyproject.toml
  requirements.txt
Labels: feature

#32 Add `branch_name` as an option to `benchbase_clone` (default: main).
  dodos/benchbase.py
Labels: infrastructure
