Repository cmu-db/noisepage-pilot, pull requests merged in 2022-02, with the labels that each got.

#31 Add support for parameter sweeps in training data generation.
  behavior/datagen/gen.py
  behavior/modeling/train.py
  behavior/plans/diff.py
  config/behavior/default.yaml
  evaluation/__init__.py
  evaluation/utils.py
Labels: ready-for-review, feature

#33 Project 1: PostgreSQL Auto Tuner grading script.
  project/project1.sh
Labels: ready-for-review

#34 Add `database_game` support for recording inference results (`record_predictions`, default off).
  action/selection/open_spiel/database.cc
  action/selection/open_spiel/database.h
  action/selection/open_spiel/database_game.cc
  behavior/microservice/app.py
  behavior/microservice/static/bootstrap.min.css
  behavior/microservice/static/dataTables.bootstrap5.min.css
  behavior/microservice/static/dataTables.bootstrap5.min.js
  behavior/microservice/static/jquery-3.6.0.min.js
  behavior/microservice/static/jquery.dataTables.min.js
  behavior/microservice/templates/base.html
  behavior/microservice/templates/index.html
  pyproject.toml
Labels: ready-for-review, feature

#36 Fix paths so that microservice artifacts go into their own folder.
  behavior/microservice/app.py
  dodos/behavior.py
Labels: best-practice

#38 Project 1: Additional help for working with NoisePage-Pilot.
  dodo.py
  dodos/project1.py
  project/README.md
  project/project1.sh
Labels: infrastructure

#39 Fix preprocessor parameter substitution code.
  forecast/preprocessor.py
Labels: bug

#37 ExplainMicroserviceCost Performance Improvements
  action/selection/open_spiel/database.cc
  behavior/microservice/app.py
Labels: ready-for-review, performance

#41 Project 1: use simple query protocol by default.
  project/project1.sh
Labels: ready-for-review

#42 NoisePage Startup and Datagen Configuration Patches
  behavior/README.md
  behavior/datagen/gen.py
  config/behavior/datagen.yaml
  config/behavior/modeling.yaml
  config/postgres/default_postgresql.conf
  config/postgres/dev4_postgresql.conf
  dodos/behavior.py
  dodos/noisepage.py
Labels: ready-for-review, infrastructure

#47 Project 1: Update Quickstart README's preferQueryMode (extended -> simple).
  project/README.md
Labels: best-practice

#46 Fix Preprocessor's substitute_params by reversing substitution order.
  forecast/preprocessor.py
Labels: ready-for-review, bug

#45 Fix OpenSpiel forecast parsing code.
  action/selection/open_spiel/database.cc
Labels: ready-for-review, bug

#44 Add Preprocessor support for directly outputting query templates and queries.
  forecast/preprocessor.py
Labels: ready-for-review, feature

#43 Project 1: add workload CSV support; add pg_isready calls.
  dodos/project1.py
  project/project1.sh
Labels: ready-for-review, infrastructure
